# -*- coding: utf-8 -*-
"""Swara.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zox9TMhqbAtXtaloRjUYMicAv21lQ_rt

Day 1
"""

import numpy as np

# Input
x = np.array([2, 3])

# Weights
w = np.array([0.5, 0.2])

# Bias
b = 1

# Weighted sum
z = np.dot(x, w) + b

# Step activation
if z >= 0:
    output = 1
else:
    output = 0

print("Input:", x)
print("Weights:", w)
print("Bias:", b)
print("Weighted Sum:", z)
print("Output:", output)

"""Day 2"""

import numpy as np

# Input
x = np.array([2, 3])

# Hidden layer weights
w1 = np.array([[0.5, 0.2],
               [0.4, 0.6]])

# Bias
b1 = np.array([1, 1])

# Forward calculation
z1 = np.dot(x, w1) + b1

# ReLU activation
a1 = np.maximum(0, z1)

print("Input:", x)
print("Hidden layer value:", z1)
print("After ReLU:", a1)

"""Day 3"""

import numpy as np

# Input
x = 2

# Actual output
y = 1

# Initial weight
w = 0.5

# Learning rate
lr = 0.1

# Prediction
prediction = x * w

# Error
error = y - prediction

# Gradient
gradient = -2 * x * error

# Update weight
w = w - lr * gradient

print("Prediction:", prediction)
print("Error:", error)
print("Gradient:", gradient)
print("Updated Weight:", w)

"""Day 4"""

import numpy as np

x = np.array([-2, -1, 0, 1, 2])

# Sigmoid
sigmoid = 1 / (1 + np.exp(-x))

# Tanh
tanh = np.tanh(x)

# ReLU
relu = np.maximum(0, x)

print("Input:", x)
print("Sigmoid:", sigmoid)
print("Tanh:", tanh)
print("ReLU:", relu)

# Softmax
values = np.array([2.0, 1.0, 0.5])
exp_values = np.exp(values)
softmax = exp_values / np.sum(exp_values)

print("Softmax:", softmax)
print("Softmax Sum:", np.sum(softmax))

"""Day 5"""

import numpy as np
import tensorflow as tf

# Data
X = np.array([
    [1, 2],
    [2, 3],
    [3, 4],
    [4, 5],
    [5, 6],
    [6, 7]
])

y = np.array([0, 0, 0, 1, 1, 1])

# Create ANN
model = tf.keras.Sequential([
    tf.keras.layers.Dense(4, activation='relu', input_shape=(2,)),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

# Compile
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# Train
model.fit(X, y, epochs=10, verbose=0)

# Evaluate
loss, accuracy = model.evaluate(X, y, verbose=0)

print("Loss:", loss)
print("Accuracy:", accuracy)

"""Day 6"""

import tensorflow as tf
import numpy as np

X = np.array([
    [1],
    [2],
    [3],
    [4],
    [5]
])

y = np.array([
    [2],
    [4],
    [6],
    [8],
    [10]
])

model = tf.keras.Sequential([
    tf.keras.layers.Dense(8, activation='relu', input_shape=(1,)),
    tf.keras.layers.Dense(1)
])

model.compile(
    optimizer='adam',
    loss='mse'
)

history = model.fit(
    X, y,
    epochs=20,
    verbose=0
)

print("Initial Loss:", history.history['loss'][0])
print("Final Loss:", history.history['loss'][-1])
print("Training completed")

"""Day 7"""

import numpy as np
import pandas as pd
import tensorflow as tf

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix

# 1. Create simple customer data
data = pd.DataFrame({
    "Tenure": [2,5,1,8,10,3,7,12,4,9,
               1,6,11,2,8,5,13,3,10,7],

    "MonthlyCharges": [80,60,90,40,35,75,50,30,70,45,
                       95,55,32,85,42,65,28,88,38,52],

    "Spend": [160,300,90,320,350,225,350,360,280,405,
              95,330,352,170,336,325,364,264,380,364],

    "Churn": [1,0,1,0,0,1,0,0,1,0,
              1,0,0,1,0,1,0,1,0,0]
})

print("Customer Data:")
print(data.head())

# 2. Features and target
X = data[["Tenure", "MonthlyCharges", "Spend"]]
y = data["Churn"]

# 3. Split data
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

# 4. Scale features
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# 5. Build ANN
model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(3,)),
    tf.keras.layers.Dense(8, activation="relu"),
    tf.keras.layers.Dense(4, activation="relu"),
    tf.keras.layers.Dense(1, activation="sigmoid")
])

# 6. Compile model
model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

# 7. Train model
model.fit(
    X_train,
    y_train,
    epochs=50,
    verbose=0
)

# 8. Test model
loss, accuracy = model.evaluate(
    X_test,
    y_test,
    verbose=0
)

print("\nTest Loss:", loss)
print("Test Accuracy:", accuracy)

# 9. Prediction
probability = model.predict(
    X_test,
    verbose=0
)

prediction = (probability > 0.5).astype(int)

# 10. Final accuracy
final_accuracy = accuracy_score(
    y_test,
    prediction
)

print("\nFinal Accuracy:", final_accuracy)

# 11. Confusion Matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, prediction))

print("\nANN CUSTOMER CHURN PROJECT COMPLETED!")